apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: ecommerce
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://ecommerce-rds.chw02o422fp4.ap-south-1.rds.amazonaws.com:3306/ecommerce
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_DATASOURCE_PASSWORD: admin123

